### ISSUE TITLE
Tado component not loading after upgrading to HA 0.39.2

### ISSUE THREAD

**Issue by imtiajmeah** [wmalgadey/tado_component#10]
Hi Guys,

Anyone else having the same errors as below after upgrading to HA 0.39.2

17-03-02 16:27:20 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.tado_v1. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/loader.py", line 141, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/tado_v1.py", line 8, in <module>
    from homeassistant.components.discovery import load_platform
ImportError: cannot import name 'load_platform'
17-03-02 16:27:20 ERROR (MainThread) [homeassistant.loader] Unable to find component tado_v1

**Comment by covrig** [comment]
Same here. I was going nuts with this until I saw your message here. **Thank you!!**
I was trying to install this on a new machine.

**Comment by covrig** [comment]
@wmalgadey Any update on this? Thanks.

**Comment by wmalgadey** [comment]
Sorry for not getting to this. I was the last 10days out of office. I'll have time tomorrow.

**Comment by covrig** [comment]
Thanks for the update. I didn't know if this the correct git anymore.

**Comment by AndiH** [comment]
@wmalgadey In homeassistant's commit #4e96e46 the `load_platform` import from `homeassistant.helpers.discovery` in `homeassistant.components.discovery` was changed to `async_load_platform`. With this, `load_platform` is not available anymore in the *helpers.discovery*. https://github.com/home-assistant/home-assistant/commit/0ac4a152bec0f6d0bd3f5d3314514b5ec9ca8932

Since I have no clue of any of the homeassistant infrastructure, I do not really know how to react to this. Maybe you want to import `load_platform` from `homeassistant.helpers.discovery` and not `homeassistant.components.discovery`?

**Comment by wmalgadey** [comment]
I will first check this repository. After that I will do another try on merging it to the main ha repository.

@AndiH thanks for this information. I will check that first.

**Comment by wmalgadey** [comment]
v0.1.1 solved this problem
