### ISSUE TITLE
No sensor updates after 60 minutes

### ISSUE THREAD

**Issue by syssi** [wmalgadey/tado_component#11]
After an hour of operation the Tado API returns error 400 ("Bad request"). I have started HA yesterday at 11:20 pm. Exact 1 hour later the sensor update fails with

```
17-03-14 00:19:23 ERROR (MainThread) [homeassistant.components.sensor] Error while update entity from tado_v1 in sensor
Traceback (most recent call last):
  File "/var/hass/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 428, in _update_entity_states
    yield from update_coro
  File "/var/hass/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 207, in async_update_ha_state
    yield from self.hass.loop.run_in_executor(None, self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/hass/homeassistant-2/custom_components/sensor/tado_v1.py", line 114, in update
    self._tado_data.update()
  File "/var/hass/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/var/hass/homeassistant-2/custom_components/sensor/tado_v1.py", line 235, in _update
    data = self._tado.getState(sensor["id"])
  File "/var/hass/homeassistant-2/deps/PyTado/interface.py", line 169, in getState
    data = self._apiCall(cmd)
  File "/var/hass/homeassistant-2/deps/PyTado/interface.py", line 45, in _apiCall
    self._refresh_token()
  File "/var/hass/homeassistant-2/deps/PyTado/interface.py", line 105, in _refresh_token
    response = self.opener.open(req)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Kind regards,

Sebastian

**Comment by wmalgadey** [comment]
ihhh. hope that tado does not detect our "foreign access" and blocks us? I will look, if this happens on my side too.

**Comment by syssi** [comment]
I talked with tado about the API recently and they told me I should use pytado. ;-) I'm curious.

**Comment by diplix** [comment]
i’m still undecided whether tado sometimes blocks (excessive) access (or what they think might be excessive) or of there’s a technical problem (bug) on tado’s side. when i started querying my tado account half a year ago, i was usally blocked after 24 hours. curiously the blocking resulted in a completly inaccessible tado-bridge, that would not be accessable any more, locally or remotly. restarting the bridge usally solved the problem. 

this has been getting better over the past months. i need to restart the bridge only every few weeks.

however the problems i observed may be ompletly unrelated to what you reported here.

**Comment by syssi** [comment]
tado_component polls the API every 10 seconds. I assume the interval is based on the angular app at my.tado.com which is using the same. I'm talking to the API with another application (2min update interval) since two month without problems. My tado bridge is stable. No reboots required.

**Comment by wmalgadey** [comment]
I will add some logging to the pytado-api I am using.


PS: Gehe ich eigentlich richtig in der Annahme, dass wir drei hier des deutschen mächtig sind? Wenn ja dann erstmal "Hallo" und wir können ja gerne beim englischen bleiben :)

**Comment by diplix** [comment]
i have a newer bridge, the one that is supposed to handle homekit. maybe my issues were related to some glitches with that version of the bridge.

ansonsten: „hallo!“ :)

**Comment by syssi** [comment]
I'm using the old bridge without the button.

Hallo zusammen! :-)

**Comment by syssi** [comment]
@diplix is right. It's a rate limit. If I stop another process doing tado-api calls (2min interval + re-login everytime) next to tado_component the connection does not collapse anymore.
