### ISSUE TITLE
Issues After HA Update to 0.40.1

### ISSUE THREAD

**Issue by eximo84** [wmalgadey/tado_component#12]
```
17-03-16 12:01:20 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.tado_v1. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/loader.py", line 141, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/tado_v1.py", line 8, in <module>
    from homeassistant.components.discovery import load_platform
ImportError: cannot import name 'load_platform'
17-03-16 12:01:20 ERROR (MainThread) [homeassistant.loader] Unable to find component tado_v1
17-03-16 12:01:20 ERROR (MainThread) [homeassistant.setup] Setup failed for tado_v1: Component not found.
```

**Comment by wmalgadey** [comment]
did you use the latest release? I just changed this in alpha.2 (https://github.com/wmalgadey/tado_component/releases/tag/v0.1.1)

**Comment by wmalgadey** [comment]
I am closing it, because this issue has been adressed before in #10
