### ISSUE TITLE
climate.set_operation_mode does not accept some modes

### ISSUE THREAD

**Issue by syssi** [wmalgadey/tado_component#15]
I tried to turn a zone "off" today. This works fine. My automation looks like:

```
  - alias: Turn off radiator if window is open
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_xxxxxxxxxxxxxx
      to: 'on'
    action:
      service: climate.set_operation_mode
      entity_id: climate.bedroom
      data:
        operation_mode: 'Off'
```
If I go back to "Smart schedule" or "Tado mode" the home-assistant.log shows following error: 

```
17-04-13 23:02:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/var/hass/lib/python3.4/site-packages/homeassistant/core.py", line 1014, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/var/hass/lib/python3.4/site-packages/homeassistant/components/climate/__init__.py", line 362, in async_operation_set_service
    yield from climate.async_set_operation_mode(operation_mode)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/hass/lib/python3.4/site-packages/homeassistant/components/climate/tado.py", line 176, in set_operation_mode
    self._control_heating()
  File "/var/hass/lib/python3.4/site-packages/homeassistant/components/climate/tado.py", line 290, in _control_heating
    self.zone_id, self._current_operation, self._target_temp)
  File "/var/hass/lib/python3.4/site-packages/homeassistant/components/tado.py", line 127, in set_zone_overlay
    return self.tado.setZoneOverlay(zone_id, mode, temperature, duration)
  File "/var/hass/homeassistant-2/deps/PyTado/interface.py", line 250, in setZoneOverlay
    data = self._apiCall(cmd, "PUT", post_data, True)
  File "/var/hass/homeassistant-2/deps/PyTado/interface.py", line 63, in _apiCall
    response = self.opener.open(req)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

The drop-down shows always "Smart schedule" even if the zone is "off".

**Comment by wmalgadey** [comment]
I will try to look into this. The http error 422 is created by my.tado.com. But, because the api I use is not officially public, I don't have propper information on why this happens.

**Comment by syssi** [comment]
May be this helps: Going back from "Off" to "Tado mode" on my.tado.com (the angular web-interface) looks like this:

```
curl 'https://my.tado.com/api/v2/homes/123123/zones/1/overlay' -X DELETE --data-binary '{}' \
-H 'Pragma: no-cache' -H 'Origin: https://my.tado.com' \
-H 'Accept-Encoding: gzip, deflate, sdch, br' \
-H 'Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4' \
-H 'Authorization: Bearer *redacted*' \
-H 'Content-Type: text/plain;charset=UTF-8' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Cache-Control: no-cache' \
-H 'X-Requested-With: XMLHttpRequest' \
-H 'Cookie: redacted*' \
-H 'Connection: keep-alive' \
-H 'Referer: https://my.tado.com/' \
--compressed
```
It's just a DELETE of the Overlay plus the payload "{}". I don't know how to trace the urllib/request of the tado component to compare.

**Comment by syssi** [comment]
I had a clue: Turning off a zone by set_operation_mode = off is not recognized properly. If the tado component updates the state of the zone the operation mode remains "smart schedule". At this point HA and my.tado.com are out of sync. Switching between "manual" and "smart schedule" works fine.

**Comment by syssi** [comment]
In the meantime this automation does the job as well. May be somebody can need it:

```
  # if one of the window is opened -> turn off the radiator
  - alias: Turn off the radiator if a window is opened (livingroom)
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001xxxxxx
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001yyyyyy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001zzzzzz
        to: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.livingroom
        data:
          temperature: 5

  # if all windows are closed again -> turn on
  - alias: Turn on radiator if the windows are closed (livingroom)
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001xxxxxx
        to: 'off'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001yyyyyy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001zzzzzz
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.door_window_sensor_158d0001xxxxxx
          state: 'off'
        - condition: state
          entity_id: binary_sensor.door_window_sensor_158d0001yyyyyy
          state: 'off'
        - condition: state
          entity_id: binary_sensor.door_window_sensor_158d0001zzzzzz
          state: 'off'
    action:
      service: climate.set_operation_mode
      entity_id: climate.livingroom
      data:
        operation_mode: 'Smart schedule'
```

**Comment by agross** [comment]
Thank you, I'm seeing this error as well.

When I set the operation mode to "Off" using the HA web UI, it turns back to "Smart schedule" after a couple of seconds.

I was able to execute the request manually with `climate.set_operation_mode` and `{"entity_id": "climate.alex", "operation_mode":"Off" }` and tado's web UI show's "Off", but HA still displays "Smart schedule".

**Comment by agross** [comment]
@wmalgadey Any update on this? I cannot update HASS because of this issue. :(

**Comment by wmalgadey** [comment]
I am on it :) need a way to see the requests made to my.tado.com from pytado. I added logging to pytado, but cannot see this in hass!

**Comment by agross** [comment]
Please let me know how I can help!

**Comment by wmalgadey** [comment]
I made a progress in this! Now I have to analyse, why my.tado.com is rejecting the request to change the operation mode!

**Comment by agross** [comment]
Hi @wmalgadey,

could you make any progress on this? I would love to see this fixed before the cold season starts on the northern hemisphere. :)

Right now one is required to update HASS because of the changes to the authentication mode that tado rolled our last week.

Let me know if I can help!

**Comment by wmalgadey** [comment]
Is the problem still present?

**Comment by agross** [comment]
Yes:

```
2017-07-09 13:43:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.alex fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/climate/tado.py", line 299, in update
    cooling = overlay_data['setting']['mode'] == 'COOL'
KeyError: 'mode'
```

**Comment by wmalgadey** [comment]
ohh! but the error message changed ;)

this should be something I can change!

Is it possible for you to get me some data from your browser, when you open my.tado.com? for your zone called `alex`?

I need the `state`-request.

**Comment by agross** [comment]
Sure: 

```json
{
  "tadoMode": "HOME",
  "geolocationOverride": false,
  "geolocationOverrideDisableTime": null,
  "preparation": null,
  "setting": {
    "type": "HEATING",
    "power": "OFF",
    "temperature": null
  },
  "overlayType": "MANUAL",
  "overlay": {
    "type": "MANUAL",
    "setting": {
      "type": "HEATING",
      "power": "OFF",
      "temperature": null
    },
    "termination": {
      "type": "MANUAL",
      "projectedExpiry": null
    }
  },
  "openWindow": null,
  "link": {
    "state": "ONLINE"
  },
  "activityDataPoints": {
    "heatingPower": {
      "type": "PERCENTAGE",
      "percentage": 0.00,
      "timestamp": "2017-07-09T11:59:41.111Z"
    }
  },
  "sensorDataPoints": {
    "insideTemperature": {
      "celsius": 26.26,
      "fahrenheit": 79.27,
      "timestamp": "2017-07-09T11:51:34.251Z",
      "type": "TEMPERATURE",
      "precision": {
        "celsius": 1.0,
        "fahrenheit": 1.0
      }
    },
    "humidity": {
      "type": "PERCENTAGE",
      "percentage": 51.10,
      "timestamp": "2017-07-09T11:51:34.251Z"
    }
  }
}
```

**Comment by wmalgadey** [comment]
can you send me one again for a state where the overlay mode is set? Currently your zone is manually turned off. The error you are experiencing should only occur if the the device or zone is active.

**Comment by agross** [comment]
The zone has an overlay set. I don't know what you mean, can you please elaborate?

(I use HASS to set overlays and remove them when people leave my network or return - this way tado  supports shared flat scenaros properly. By default tado heats all zones when somebody is home, but in our case I want my room only to heat up only when I am home, not somebody else.)

**Comment by wmalgadey** [comment]
The json you send says:

```json
  "overlay": {
    "type": "MANUAL",
    "setting": {
      "type": "HEATING",
      "power": "OFF",
      "temperature": null
    },
    "termination": {
      "type": "MANUAL",
      "projectedExpiry": null
    }
  },
```

this means, you did changed the setting of the zone to "OFF" and it will be "terminated" manually (not by time or by the tado smart schedule!"

**Comment by agross** [comment]
Yes, termination is determined by presence in the nmap scan.

It's still not clear what I should do/send you. Please explain :)

**Comment by wmalgadey** [comment]
hmm! The error you send 

```
  File "/usr/src/app/homeassistant/components/climate/tado.py", line 299, in update
    cooling = overlay_data['setting']['mode'] == 'COOL'
KeyError: 'mode'
```

it occurs in line 299!

Line 299 should only be reached, when the zone is active and not "OFF". So with the json you send me (where the zone is "OFF", because of the overlay) I cannot check if my fix will work.

But I made the fix now, because I suppose the state response not always includes the property I was expecting. Therefore I made some more if-statements. 

So no action needed from you now ;) Just check if my fix (eea9ea3ac55c6b7ec0e3eb2b17604024a3651577) works!

**Comment by agross** [comment]
So I'll wait for a new HASS release, or how do you test your own changes? `custom_components`?

**Comment by wmalgadey** [comment]
The change to HASS will take some time, because I need to create a merge request.

This component could be installed side by side to the hass component. First read:

   https://github.com/wmalgadey/tado_component/blob/master/README.md

After you installed this custom component, you have to change the configuration to use `tado_v1:` in of just `tado:`.

**Comment by syssi** [comment]
I've tested commit adfb608f86b8bf4c1c43e71b4067cbfe1de9ba85. It works but there is some small glitch:

```
2017-07-09 17:02:16 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.livingroom fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/climate/tado.py", line 299, in update
    setting = setting is not None
UnboundLocalError: local variable 'setting' referenced before assignment
```

**Comment by wmalgadey** [comment]
Ok! Sorry for this. Happens when you do not use your own shit ;)

a14a1c6f15d13f178757ea9142f0374622a9d733 fixes this
