### ISSUE TITLE
UnboundLocalError: local variable 'setting' referenced before assignment

### ISSUE THREAD

**Issue by agross** [wmalgadey/tado_component#22]
Updated to HA 0.50.2 today and got this during startup:

```
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/climate/tado.py", line 291, in update
    setting = setting is not None
UnboundLocalError: local variable 'setting' referenced before assignment
```

**Comment by syssi** [comment]
It's already fixed with https://github.com/wmalgadey/tado_component/issues/21. The next release includes the fix.

**Comment by agross** [comment]
Thanks! 👍
